### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by sm-sami** [kanakshilledar/devlink#1]
## Auth
- [x] POST /user/create
- [x] POST /user/sign-in

## User
- [x] GET /user
- [x] PATCH /user (if required)

## Events
- [x] GET /event/all
- [x] GET /event/user/:id
- [x] GET /event/:id
- [x] POST /event
- [x] PATCH /event/:id

**Comment by kanakshilledar** [comment]
can you clarify the endpoint?
GET /event/user/:id

**Comment by sm-sami** [comment]
> can you clarify the endpoint? GET /event/user/:id

To get the all events created by a user

**Comment by kanakshilledar** [comment]
All the endpoints are created hence closing this issue.
